### ISSUE TITLE
rqt_graph error

### ISSUE THREAD

**Issue by acowley** [lopsided98/nix-ros-overlay#143]
Trying to run `rqt_graph` from noetic results in,

```
$ rqt_graph
CompositePluginProvider.discover() could not discover plugins from provider "<class 'qt_gui.recursive_plugin_provider.RecursivePluginProvider'>":
Traceback (most recent call last):
  File "/nix/store/z4k8gh0r87h4015dghp34pv7c6lf2p9r-ros-noetic-qt-gui-0.4.2-r1/lib/python3.9/site-packages/qt_gui/composite_plugin_provider.py", line 57, in discover
    plugin_descriptors = plugin_provider.discover(discovery_data)
  File "/nix/store/z4k8gh0r87h4015dghp34pv7c6lf2p9r-ros-noetic-qt-gui-0.4.2-r1/lib/python3.9/site-packages/qt_gui/recursive_plugin_provider.py", line 53, in discover
    plugin_descriptors = self._plugin_provider.discover(discovery_data)
  File "/nix/store/dxsk9ddd6asj7bv5vaf72b7z5jyin3f7-ros-noetic-rqt-gui-0.5.2-r1/lib/python3.9/site-packages/rqt_gui/ros_plugin_provider.py", line 67, in discover
    plugin_descriptors += self._parse_plugin_xml(package_name, plugin_xml)
  File "/nix/store/dxsk9ddd6asj7bv5vaf72b7z5jyin3f7-ros-noetic-rqt-gui-0.5.2-r1/lib/python3.9/site-packages/rqt_gui/ros_plugin_provider.py", line 128, in _parse_plugin_xml
    for library_el in root.getiterator('library'):
AttributeError: 'ElementTree' object has no attribute 'getiterator'
```

[This](https://stackoverflow.com/a/65138248/277078) suggests it's an incompatibility with python 3.9. So I rebuilt everything with `python38`, and `rqt_graph` now works.

I don't know if the way I did this is the right way, so I'm open to advice before opening a PR. What I did was set `python = python38;` in the `noetic` expression in `distros/default.nix`, and then `python3 = pythonOverridesFor self.python38;` in the `base` expression in `distros/distro-overlay.nix`. I do not know if the latter change was needed, but I can't test it right now as rebuilding everything takes quite a while.

If this looks right, I'll open a PR to make this change.

**Comment by lopsided98** [comment]
This has been fixed upstream so the proper fix is to include the patch: https://github.com/ros-visualization/rqt/pull/241
