### ISSUE TITLE
rqt error under foxy, missing resource file?

### ISSUE THREAD

**Issue by walshbp** [lopsided98/nix-ros-overlay#148]
I am new to both ros and nix.  I am unable to get rqt to launch under foxy.   I'm hoping someone can point me in the right direction.    rqt throws the following:

```
Traceback (most recent call last):
  File "/nix/store/q83b273cy1wvwn8wx3kq59355394l19d-python3.9-ros-foxy-rqt-gui-1.1.2-r1/bin/.rqt-wrapped", line 8, in <module>
    sys.exit(main())
  File "/nix/store/rka0fnjhlf4bwjkzw8qhn9wm8s1d708p-ros-env/lib/python3.9/site-packages/rqt_gui/main.py", line 87, in main
    sys.exit(Main().main())
  File "/nix/store/rka0fnjhlf4bwjkzw8qhn9wm8s1d708p-ros-env/lib/python3.9/site-packages/rqt_gui/main.py", line 57, in main
    return super(
  File "/nix/store/4k5axw6iwisx4jzzg2k8nyh0s6s7cbg4-ros-foxy-qt-gui-1.1.3-r1/lib/python3.9/site-packages/qt_gui/main.py", line 447, in main
    app = self.create_application(argv)
  File "/nix/store/rka0fnjhlf4bwjkzw8qhn9wm8s1d708p-ros-env/lib/python3.9/site-packages/rqt_gui/main.py", line 64, in create_application
    rqt_gui_path = get_package_path('rqt_gui')
  File "/nix/store/4k5axw6iwisx4jzzg2k8nyh0s6s7cbg4-ros-foxy-qt-gui-1.1.3-r1/lib/python3.9/site-packages/qt_gui/ros_package_helper.py", line 35, in get_package_path
    _, package_path = get_resource('packages', name)
  File "/nix/store/rka0fnjhlf4bwjkzw8qhn9wm8s1d708p-ros-env/lib/python3.9/site-packages/ament_index_python/resources.py", line 49, in get_resource
    raise LookupError(
LookupError: Could not find the resource 'rqt_gui' of type 'packages'
```

For my nix file, I've modified examples/ros2-basic.nix:

```
with import ../. {};
with rosPackages.foxy;

mkShell {
  nativeBuildInputs = [
    (buildEnv {
      paths = [
        ros-environment
        ros2topic
        ros2node
        rqt
        rqt-gui
        rqt-action
        rqt-common-plugins
        geometry-msgs
        rmw-fastrtps-dynamic-cpp
      ];
    })
  ];

  RMW_IMPLEMENTATION = "rmw_fastrtps_dynamic_cpp";
}
```
Playing with the rqt python code a bit, it appears that it is looking for a "rqt_gui" resource file in a "ament_index/resource_index/packages/" subdirectory.  No such file exists under my /nix/store directory.

How do I install the rqt_gui resource file?  Was that suppose to be installed as part of the rqt_gui package? or am I missing another package?

Thanks,

Bryan

**Comment by lopsided98** [comment]
That file is installed, it just wasn't on `AMENT_PREFIX_PATH`. I added the buildEnv environment to `AMENT_PREFIX_PATH` in the wrappers, which should fix your problem.
