### ISSUE TITLE
Issue with SIP building ROS2 Foxy qt-gui-cpp

### ISSUE THREAD

**Issue by molysgaard** [lopsided98/nix-ros-overlay#224]
There seems to be an issue with SIP for building some of the packages.

# How to reproduce

Content of `test.nix`
```nix
# Environment containing basic ROS2 tools

with import /home/myuser/conf/nix/nix-ros-overlay/. {};
with rosPackages.foxy;

mkShell {
  nativeBuildInputs = [
    (buildEnv {
      paths = [
        qt-gui-cpp
      ];
    })
  ];
}
```

Running the following command in `nix-shell test.nix` gives the following error:
```
/home/myuser/proj/ros2-scratch〉nix-shell test.nix                                                                                                                                                                     11/09/2022 10:28:40 AM
these 2 derivations will be built:
  /nix/store/jbnxd3mvyabazc11kms7qkgaxkx27n2d-ros-foxy-qt-gui-cpp-1.1.3-r1.drv
  /nix/store/dxh43j8n9g5sf3n0l71adh8h653bmpr9-ros-env.drv
building '/nix/store/jbnxd3mvyabazc11kms7qkgaxkx27n2d-ros-foxy-qt-gui-cpp-1.1.3-r1.drv'...
qtPreHook
unpacking sources
unpacking source archive /nix/store/4z5jdcjl32l00d07dqfwjzw0r0lns0j6-1.1.3-1.tar.gz
source root is qt_gui_core-release-release-foxy-qt_gui_cpp-1.1.3-1
setting SOURCE_DATE_EPOCH to timestamp 1630449517 of file qt_gui_core-release-release-foxy-qt_gui_cpp-1.1.3-1/test/test_imports.py
patching sources
configuring
fixing cmake files...
cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDIR=/nix/store/ml9lnrdaihan2x9m1nxhb8ahfa4kp1d8-ros-foxy-qt-gui-cpp-1.1.3-r1/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/ml9lnrdaihan2x9m1nxhb8ahfa4kp1d8-ros-foxy-qt-gui-cpp-1.1.3-r1/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/ml9lnrdaihan2x9m1nxhb8ahfa4kp1d8-ros-foxy-qt-gui-cpp-1.1.3-r1/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/ml9lnrdaihan2x9m1nxhb8ahfa4kp1d8-ros-foxy-qt-gui-cpp-1.1.3-r1/share/doc/qt_gui_cpp -DCMAKE_INSTALL_INFODIR=/nix/store/ml9lnrdaihan2x9m1nxhb8ahfa4kp1d8-ros-foxy-qt-gui-cpp-1.1.3-r1/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/ml9lnrdaihan2x9m1nxhb8ahfa4kp1d8-ros-foxy-qt-gui-cpp-1.1.3-r1/share/man -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/ml9lnrdaihan2x9m1nxhb8ahfa4kp1d8-ros-foxy-qt-gui-cpp-1.1.3-r1/include -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/ml9lnrdaihan2x9m1nxhb8ahfa4kp1d8-ros-foxy-qt-gui-cpp-1.1.3-r1/include -DCMAKE_INSTALL_SBINDIR=/nix/store/ml9lnrdaihan2x9m1nxhb8ahfa4kp1d8-ros-foxy-qt-gui-cpp-1.1.3-r1/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/ml9lnrdaihan2x9m1nxhb8ahfa4kp1d8-ros-foxy-qt-gui-cpp-1.1.3-r1/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/ml9lnrdaihan2x9m1nxhb8ahfa4kp1d8-ros-foxy-qt-gui-cpp-1.1.3-r1/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_SYSROOT= -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_STRIP=/nix/store/2bg235ac1s6cpxwr1pjagn6bj8q2425l-gcc-wrapper-11.3.0/bin/strip -DCMAKE_RANLIB=/nix/store/2bg235ac1s6cpxwr1pjagn6bj8q2425l-gcc-wrapper-11.3.0/bin/ranlib -DCMAKE_AR=/nix/store/2bg235ac1s6cpxwr1pjagn6bj8q2425l-gcc-wrapper-11.3.0/bin/ar -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/nix/store/ml9lnrdaihan2x9m1nxhb8ahfa4kp1d8-ros-foxy-qt-gui-cpp-1.1.3-r1  -DAMENT_CMAKE_ENVIRONMENT_PARENT_PREFIX_PATH_GENERATION:BOOL=OFF -DPython3_EXECUTABLE:FILEPATH=/nix/store/xcaaly5shfy227ffs8nipxrd49b56iqq-python3-3.10.8/bin/python3.10 -DAMENT_CMAKE_ENVIRONMENT_PARENT_PREFIX_PATH_GENERATION:BOOL=OFF -DPython3_EXECUTABLE:FILEPATH=/nix/store/xcaaly5shfy227ffs8nipxrd49b56iqq-python3-3.10.8/bin/python3.10 
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /nix/store/2bg235ac1s6cpxwr1pjagn6bj8q2425l-gcc-wrapper-11.3.0/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /nix/store/2bg235ac1s6cpxwr1pjagn6bj8q2425l-gcc-wrapper-11.3.0/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ament_cmake: 0.9.11 (/nix/store/d741ygnlm808xapq88xqv89adr0d0ffc-ros-foxy-ament-cmake-0.9.11-r1/share/ament_cmake/cmake)
-- Found PythonInterp: /nix/store/xcaaly5shfy227ffs8nipxrd49b56iqq-python3-3.10.8/bin/python3 (found suitable version "3.10.8", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /nix/store/xcaaly5shfy227ffs8nipxrd49b56iqq-python3-3.10.8/bin/python3
-- Found pluginlib: 2.5.4 (/nix/store/cjwdz02mfh0qv0q1lgwy5sz8rlzy7n6a-ros-foxy-pluginlib-2.5.4-r1/share/pluginlib/cmake)
-- Found TinyXML2: /nix/store/lljw2gqdnvmwzqawm0fpljr6kzyplvnz-tinyxml-2-6.0.0/lib/libtinyxml2.so  
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
-- Found PythonLibs: /nix/store/xcaaly5shfy227ffs8nipxrd49b56iqq-python3-3.10.8/lib/libpython3.10.so (found suitable version "3.10.8", minimum required is "3.10") 
-- Found python_qt_binding: 1.0.6 (/nix/store/020p6iibmh7r3qwvwq1g30w97sz3nw4q-ros-foxy-python-qt-binding-1.0.6-r2/share/python_qt_binding/cmake)
-- Shiboken binding generator NOT available.
-- Found python_qt_binding: 1.0.6 (/nix/store/020p6iibmh7r3qwvwq1g30w97sz3nw4q-ros-foxy-python-qt-binding-1.0.6-r2/share/python_qt_binding/cmake)
-- Found PythonInterp: /nix/store/xcaaly5shfy227ffs8nipxrd49b56iqq-python3-3.10.8/bin/python3 (found suitable version "3.10.8", minimum required is "3.10") 
-- SIP binding generator available at: /nix/store/p42v6w950c7idkzdd0qxckd26w4dczk9-python3.10-sip-4.19.25/bin/sip
-- Python binding generators: sip
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_DOCDIR
    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_INFODIR
    CMAKE_INSTALL_LIBDIR
    CMAKE_INSTALL_LIBEXECDIR
    CMAKE_INSTALL_LOCALEDIR
    CMAKE_INSTALL_MANDIR
    CMAKE_INSTALL_OLDINCLUDEDIR
    CMAKE_INSTALL_SBINDIR
    CMAKE_POLICY_DEFAULT_CMP0025


-- Build files have been written to: /build/qt_gui_core-release-release-foxy-qt_gui_cpp-1.1.3-1/build
cmake: enabled parallel building
building
build flags: -j8 SHELL=/nix/store/y0g1mvsr6vygr61f9znljik9kl0x0inc-bash-5.1-p16/bin/bash
[ 16%] Generating __/__/include/qt_gui_cpp/moc_plugin_bridge.cpp
[ 16%] Generating __/__/include/qt_gui_cpp/moc_plugin_context.cpp
[ 16%] Generating __/__/include/qt_gui_cpp/moc_plugin.cpp
[ 44%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/plugin_provider.cpp.o
[ 44%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/settings.cpp.o
[ 44%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/composite_plugin_provider.cpp.o
[ 44%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/plugin_context.cpp.o
[ 44%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/generic_proxy.cpp.o
[ 55%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/recursive_plugin_provider.cpp.o
[ 61%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/plugin_bridge.cpp.o
[ 55%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/plugin_descriptor.cpp.o
[ 66%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/__/__/include/qt_gui_cpp/moc_plugin.cpp.o
[ 72%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/__/__/include/qt_gui_cpp/moc_plugin_bridge.cpp.o
[ 77%] Building CXX object src/qt_gui_cpp/CMakeFiles/qt_gui_cpp.dir/__/__/include/qt_gui_cpp/moc_plugin_context.cpp.o
[ 83%] Linking CXX static library libqt_gui_cpp.a
[ 83%] Built target qt_gui_cpp
[ 88%] Running SIP generator for qt_gui_cpp_sip Python bindings...
/nix/store/020p6iibmh7r3qwvwq1g30w97sz3nw4q-ros-foxy-python-qt-binding-1.0.6-r2/share/python_qt_binding/cmake/sip_configure.py:3: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
sip: /nix/store/xagdwjaig54kn9aayl9xa2r7zl3kn6zz-python3.10-PyQt5-5.15.7/lib/python3.10/site-packages/PyQt5/bindings/QtCore/QtCoremod.sip:23: syntax error
Traceback (most recent call last):
  File "/nix/store/020p6iibmh7r3qwvwq1g30w97sz3nw4q-ros-foxy-python-qt-binding-1.0.6-r2/share/python_qt_binding/cmake/sip_configure.py", line 123, in <module>
    subprocess.check_call(cmd)
  File "/nix/store/xcaaly5shfy227ffs8nipxrd49b56iqq-python3-3.10.8/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/p42v6w950c7idkzdd0qxckd26w4dczk9-python3.10-sip-4.19.25/bin/sip', '-c', '/build/qt_gui_core-release-release-foxy-qt_gui_cpp-1.1.3-1/build/sip/qt_gui_cpp_sip', '-b', '/build/qt_gui_core-release-release-foxy-qt_gui_cpp-1.1.3-1/build/sip/qt_gui_cpp_sip/pyqtscripting.sbf', '-I', '/nix/store/xagdwjaig54kn9aayl9xa2r7zl3kn6zz-python3.10-PyQt5-5.15.7/lib/python3.10/site-packages/PyQt5/bindings', '-w', '-n', 'PyQt5.sip', '-t', 'Qt_5_15_0', '-t', 'WS_X11', 'qt_gui_cpp.sip']' returned non-zero exit status 1.
make[2]: *** [src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/build.make:103: sip/qt_gui_cpp_sip/Makefile] Error 1
make[1]: *** [CMakeFiles/Makefile2:229: src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
error: builder for '/nix/store/jbnxd3mvyabazc11kms7qkgaxkx27n2d-ros-foxy-qt-gui-cpp-1.1.3-r1.drv' failed with exit code 2;
       last 10 log lines:
       > sip: /nix/store/xagdwjaig54kn9aayl9xa2r7zl3kn6zz-python3.10-PyQt5-5.15.7/lib/python3.10/site-packages/PyQt5/bindings/QtCore/QtCoremod.sip:23: syntax error
       > Traceback (most recent call last):
       >   File "/nix/store/020p6iibmh7r3qwvwq1g30w97sz3nw4q-ros-foxy-python-qt-binding-1.0.6-r2/share/python_qt_binding/cmake/sip_configure.py", line 123, in <module>
       >     subprocess.check_call(cmd)
       >   File "/nix/store/xcaaly5shfy227ffs8nipxrd49b56iqq-python3-3.10.8/lib/python3.10/subprocess.py", line 369, in check_call
       >     raise CalledProcessError(retcode, cmd)
       > subprocess.CalledProcessError: Command '['/nix/store/p42v6w950c7idkzdd0qxckd26w4dczk9-python3.10-sip-4.19.25/bin/sip', '-c', '/build/qt_gui_core-release-release-foxy-qt_gui_cpp-1.1.3-1/build/sip/qt_gui_cpp_sip', '-b', '/build/qt_gui_core-release-release-foxy-qt_gui_cpp-1.1.3-1/build/sip/qt_gui_cpp_sip/pyqtscripting.sbf', '-I', '/nix/store/xagdwjaig54kn9aayl9xa2r7zl3kn6zz-python3.10-PyQt5-5.15.7/lib/python3.10/site-packages/PyQt5/bindings', '-w', '-n', 'PyQt5.sip', '-t', 'Qt_5_15_0', '-t', 'WS_X11', 'qt_gui_cpp.sip']' returned non-zero exit status 1.
       > make[2]: *** [src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/build.make:103: sip/qt_gui_cpp_sip/Makefile] Error 1
       > make[1]: *** [CMakeFiles/Makefile2:229: src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/all] Error 2
       > make: *** [Makefile:146: all] Error 2
       For full logs, run 'nix log /nix/store/jbnxd3mvyabazc11kms7qkgaxkx27n2d-ros-foxy-qt-gui-cpp-1.1.3-r1.drv'.
error: 1 dependencies of derivation '/nix/store/dxh43j8n9g5sf3n0l71adh8h653bmpr9-ros-env.drv' failed to build
```

# Investigation

I have been doing some digging, and found other people with the same issue. There it is concluded that to properly correct the issue, a change to `nix-ros-overlay` is needed.
See this for reference:

* Question: https://github.com/NixOS/nixpkgs/pull/186612#issuecomment-1214621865
* Reply: https://github.com/NixOS/nixpkgs/pull/186612#issuecomment-1214635456

I have not had enough insight yet to see what needs to be done. I would be happy to investigate a bit more if you could point me in the right direction.

**Comment by lopsided98** [comment]
I switched from from SIP 4 to Shiboken2 and PySide2, which fixes building qt_gui_cpp. I haven't done any runtime testing yet though.
