### ISSUE TITLE
gazebo example core dump

### ISSUE THREAD

**Issue by multivac61** [lopsided98/nix-ros-overlay#395]
Running `nix develop github:lopsided98/nix-ros-overlay#example-turtlebot3-gazebo` and then `roslaunch turtlebot3_gazebo turtlebot3_world.launch` causes a coredump

Log attached below

```bash
❯ nix develop github:lopsided98/nix-ros-overlay#example-turtlebot3-gazebo
warning: ignoring untrusted substituter 'https://ros.cachix.org', you are not a trusted user.
Run `man nix.conf` for more information on the `substituters` configuration option.
warning: ignoring untrusted substituter 'https://ros.cachix.org', you are not a trusted user.
Run `man nix.conf` for more information on the `substituters` configuration option.

(failed reverse-i-search)`roslay': ^Cslaunch turtlebot3_teleop turtlebot3_teleop_key.launch

[genki@gdrn:~]$ roslaunch turtlebot3_gazebo turtlebot3_world.launch
... logging to /home/genki/.ros/log/b052cebb-fcaa-11ee-9cd4-74563c3dd882/roslaunch-gdrn-3448.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
started roslaunch server http://localhost:46209/

SUMMARY
========

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /robot_description: <?xml version="1....
 * /rosdistro: noetic
 * /rosversion: 1.16.0
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    spawn_urdf (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [3457]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to b052cebb-fcaa-11ee-9cd4-74563c3dd882
process[rosout-1]: started with pid [3466]
started core service [/rosout]
process[gazebo-2]: started with pid [3469]
process[gazebo_gui-3]: started with pid [3472]
process[spawn_urdf-4]: started with pid [3475]
[ INFO] [1713352053.896056432]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1713352053.896663930]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[ INFO] [1713352053.923953911]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1713352053.924487540]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1713352054.127229184, 0.006000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1713352054.133185553, 0.012000000]: Physics dynamic reconfigure ready.
[ INFO] [1713352054.444873039, 0.101000000]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1713352054.444894730, 0.101000000]: Starting Laser Plugin (ns = /)
[ INFO] [1713352054.446021189, 0.101000000]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1713352054.526493980, 0.101000000]: Starting plugin DiffDrive(ns = //)
[ INFO] [1713352054.526507275, 0.101000000]: DiffDrive(ns = //): <rosDebugLevel> = na
[ INFO] [1713352054.527046324, 0.101000000]: DiffDrive(ns = //): <tf_prefix> =
[ INFO] [1713352054.527270016, 0.101000000]: DiffDrive(ns = //): Advertise joint_states
[ INFO] [1713352054.527434778, 0.101000000]: DiffDrive(ns = //): Try to subscribe to cmd_vel
[ INFO] [1713352054.528018201, 0.101000000]: DiffDrive(ns = //): Subscribe to cmd_vel
[ INFO] [1713352054.528159908, 0.101000000]: DiffDrive(ns = //): Advertise odom on odom
[spawn_urdf-4] process has finished cleanly
log file: /home/genki/.ros/log/b052cebb-fcaa-11ee-9cd4-74563c3dd882/spawn_urdf-4*.log
/nix/store/wxpgfs49ia8syq5h6xa6m0ljk1sb9xvh-ros-env/lib/gazebo_ros/gzclient: line 42:  3533 Aborted                 (core dumped) GAZEBO_MASTER_URI="$desired_master_uri" GAZEBO_MODEL_DATABASE_URI="$desired_model_database_uri" gzclient $final
[gazebo_gui-3] process has died [pid 3472, exit code 134, cmd /nix/store/wxpgfs49ia8syq5h6xa6m0ljk1sb9xvh-ros-env/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/home/genki/.ros/log/b052cebb-fcaa-11ee-9cd4-74563c3dd882/gazebo_gui-3.log].
log file: /home/genki/.ros/log/b052cebb-fcaa-11ee-9cd4-74563c3dd882/gazebo_gui-3*.log
```

Here is the master.log file

```
rting new master                                                                                                                                              │   16   [rosmaster.master][INFO] 2024-04-17 11:07:34,179: publisherUpdate[/clock] -> http://localhost:37627/ ['http://localhost:45297/']
process[master]: started with pid [3457]                                                                                                                              │   17   [rosmaster.master][INFO] 2024-04-17 11:07:34,179: publisherUpdate[/clock] -> http://localhost:35623/ ['http://localhost:45297/']
ROS_MASTER_URI=http://localhost:11311                                                                                                                                 │   18   [rosmaster.master][INFO] 2024-04-17 11:07:34,180: publisherUpdate[/clock] -> http://localhost:45297/ ['http://localhost:45297/']
                                                                                                                                                                      │   19   [rosmaster.master][INFO] 2024-04-17 11:07:34,180: publisherUpdate[/clock] -> http://localhost:37627/ ['http://localhost:45297/']: sec=0.00, result=[1, '', 0]
setting /run_id to b052cebb-fcaa-11ee-9cd4-74563c3dd882                                                                                                               │   20   [rosmaster.master][INFO] 2024-04-17 11:07:34,180: publisherUpdate[/clock] -> http://localhost:35623/ ['http://localhost:45297/']: sec=0.00, result=[1, '', 0]
process[rosout-1]: started with pid [3466]                                                                                                                            │   21   [rosmaster.master][INFO] 2024-04-17 11:07:34,181: publisherUpdate[/clock] -> http://localhost:45297/ ['http://localhost:45297/']: sec=0.00, result=[1, '', 0]
started core service [/rosout]                                                                                                                                        │   22   [rosmaster.master][INFO] 2024-04-17 11:07:34,313: +CACHEDPARAM [/rosout_disable_topics_generation] by /spawn_urdf
process[gazebo-2]: started with pid [3469]                                                                                                                            │   23   [rosmaster.master][INFO] 2024-04-17 11:07:34,314: -SUB [/clock] /spawn_urdf http://localhost:37627/
process[gazebo_gui-3]: started with pid [3472]                                                                                                                        │   24   [rosmaster.master][INFO] 2024-04-17 11:07:34,314: -PUB [/rosout] /spawn_urdf http://localhost:37627/
process[spawn_urdf-4]: started with pid [3475]                                                                                                                        │   25   [rosmaster.master][INFO] 2024-04-17 11:07:34,314: -SERVICE [/spawn_urdf/get_loggers] /spawn_urdf rosrpc://localhost:37191
[ INFO] [1713352053.896056432]: Finished loading Gazebo ROS API Plugin.                                                                                               │   26   [rosmaster.master][INFO] 2024-04-17 11:07:34,314: -SERVICE [/spawn_urdf/set_logger_level] /spawn_urdf rosrpc://localhost:37191
[ INFO] [1713352053.896663930]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...                                      │   27   [rosmaster.master][INFO] 2024-04-17 11:07:34,380: publisherUpdate[/rosout] -> http://localhost:33797/ ['http://localhost:35623/', 'http://localhost:45297/']
[ INFO] [1713352053.923953911]: Finished loading Gazebo ROS API Plugin.                                                                                               │   28   [rosmaster.master][INFO] 2024-04-17 11:07:34,381: publisherUpdate[/rosout] -> http://localhost:33797/ ['http://localhost:35623/', 'http://localhost:45297/']: s
[ INFO] [1713352053.924487540]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...                                          │   29   [rosmaster.master][ERROR] 2024-04-17 11:07:34,445: Traceback (most recent call last):
[ INFO] [1713352054.127229184, 0.006000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.                                               │   30     File "/nix/store/wxpgfs49ia8syq5h6xa6m0ljk1sb9xvh-ros-env/lib/python3.11/site-packages/rosmaster/master_api.py", line 177, in validated_f
[ INFO] [1713352054.133185553, 0.012000000]: Physics dynamic reconfigure ready.                                                                                       │   31       code, msg, val = f(*newArgs, **kwds)
[ INFO] [1713352054.444873039, 0.101000000]: Laser Plugin: Using the 'robotNamespace' param: '/'                                                                      │   32                        ^^^^^^^^^^^^^^^^^^^
[ INFO] [1713352054.444894730, 0.101000000]: Starting Laser Plugin (ns = /)                                                                                           │   33     File "/nix/store/wxpgfs49ia8syq5h6xa6m0ljk1sb9xvh-ros-env/lib/python3.11/site-packages/rosmaster/master_api.py", line 435, in searchParam
[ INFO] [1713352054.446021189, 0.101000000]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""                                                                           │   34       search_key = self.param_server.search_param(caller_id, key)
[ INFO] [1713352054.526493980, 0.101000000]: Starting plugin DiffDrive(ns = //)                                                                                       │   35                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ INFO] [1713352054.526507275, 0.101000000]: DiffDrive(ns = //): <rosDebugLevel> = na                                                                                 │   36     File "/nix/store/wxpgfs49ia8syq5h6xa6m0ljk1sb9xvh-ros-env/lib/python3.11/site-packages/rosmaster/paramserver.py", line 116, in search_param
[ INFO] [1713352054.527046324, 0.101000000]: DiffDrive(ns = //): <tf_prefix> =                                                                                        │   37       raise ValueError("namespace must be global")
[ INFO] [1713352054.527270016, 0.101000000]: DiffDrive(ns = //): Advertise joint_states                                                                               │   38   ValueError: namespace must be global
[ INFO] [1713352054.527434778, 0.101000000]: DiffDrive(ns = //): Try to subscribe to cmd_vel                                                                          │   39
[ INFO] [1713352054.528018201, 0.101000000]: DiffDrive(ns = //): Subscribe to cmd_vel                                                                                 │   40   [rosmaster.master][INFO] 2024-04-17 11:07:34,446: +PUB [/scan] /gazebo http://localhost:45297/
[ INFO] [1713352054.528159908, 0.101000000]: DiffDrive(ns = //): Advertise odom on odom                                                                               │   41   [rosmaster.master][ERROR] 2024-04-17 11:07:34,526: Traceback (most recent call last):
[spawn_urdf-4] process has finished cleanly                                                                                                                           │   42     File "/nix/store/wxpgfs49ia8syq5h6xa6m0ljk1sb9xvh-ros-env/lib/python3.11/site-packages/rosmaster/master_api.py", line 177, in validated_f
log file: /home/genki/.ros/log/b052cebb-fcaa-11ee-9cd4-74563c3dd882/spawn_urdf-4*.log                                                                                 │   43       code, msg, val = f(*newArgs, **kwds)
/nix/store/wxpgfs49ia8syq5h6xa6m0ljk1sb9xvh-ros-env/lib/gazebo_ros/gzclient: line 42:  3533 Aborted                 (core dumped) GAZEBO_MASTER_URI="$desired_master_u│   44                        ^^^^^^^^^^^^^^^^^^^
ri" GAZEBO_MODEL_DATABASE_URI="$desired_model_database_uri" gzclient $final                                                                                           │   45     File "/nix/store/wxpgfs49ia8syq5h6xa6m0ljk1sb9xvh-ros-env/lib/python3.11/site-packages/rosmaster/master_api.py", line 435, in searchParam
[gazebo_gui-3] process has died [pid 3472, exit code 134, cmd /nix/store/wxpgfs49ia8syq5h6xa6m0ljk1sb9xvh-ros-env/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/h│   46       search_key = self.param_server.search_param(caller_id, key)
ome/genki/.ros/log/b052cebb-fcaa-11ee-9cd4-74563c3dd882/gazebo_gui-3.log].                                                                                            │   47                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
log file: /home/genki/.ros/log/b052cebb-fcaa-11ee-9cd4-74563c3dd882/gazebo_gui-3*.log
```

**Comment by lopsided98** [comment]
If you are not using NixOS then you need to use [nixGL](https://github.com/nix-community/nixGL) to get OpenGL working. Otherwise, I'm not sure what the problem is.
